# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env: 
      PORT: 3000
      NODE_ENV: development
      APP_NAME: chat-together
      NEXT_PUBLIC_APP_URL: http://localhost:3000
      MONGO_CONNECTSTRING: mongodb+srv://cluster0.ajuob.mongodb.net/chat-together
      MONGO_USER: toilahuong
      MONGO_PASSWORD: "@admADM1996"

      TOKEN_SECRET: toilahuong
      TOKEN_EXPIRESIN: 1h

      REFRESH_TOKEN_SECRET: toilahuong
      REFRESH_TOKEN_EXPIRESIN: 7d

      SALT_ROUNDS: 10

      REDIS_SERVER: redis://127.0.0.1:6379
      REDIS_PASSWORD: Qww+BZzs5gf42ucy
      SERVER_FILE_MANAGER: http://localhost:3001

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm i
    - run: npm run build --if-present
    - run: npm run start
